#!/bin/sh
echo "// Auto-generated by build.sh" > js/config.js
echo "const SUPABASE_URL = '$SUPABASE_URL';" >> js/config.js
echo "const SUPABASE_ANON_KEY = '$SUPABASE_ANON_KEY';" >> js/config.js
echo "const APP_CONFIG = { name: 'Stok Reagen Lab', version: '1.0.0', logsLimit: 100, toastDuration: 3000 };" >> js/config.js
echo "Build done."
