#!/bin/bash

# Script ini digunakan oleh CI/CD (Vercel/Netlify) 
# untuk membuat file js/config.js dari Environment Variables.

echo "// ============================================================" > js/config.js
echo "// js/config.js (Auto-generated by build.sh)" >> js/config.js
echo "// ============================================================" >> js/config.js
echo "" >> js/config.js
echo "const SUPABASE_URL = '$SUPABASE_URL';" >> js/config.js
echo "const SUPABASE_ANON_KEY = '$SUPABASE_ANON_KEY';" >> js/config.js
echo "" >> js/config.js
echo "const APP_CONFIG = {" >> js/config.js
echo "    name: 'Stok Reagen Lab'," >> js/config.js
echo "    version: '1.0.0'," >> js/config.js
echo "    logsLimit: 100," >> js/config.js
echo "    toastDuration: 3000," >> js/config.js
echo "};" >> js/config.js

echo "✅ js/config.js successfully generated."
